index:
    path: /
    controller: App\Controller\DefaultController::index

category:
    path: /catalog/{id}
    controller: App\Controller\DefaultController::category

categories:
    path: /catalog
    controller: App\Controller\DefaultController::category

product:
    path: /product/{id}
    controller: App\Controller\ProductController::product

cart:
    path: /cart
    controller: App\Controller\CartController::index

addcomment:
    path: /comment/add
    controller: App\Controller\DefaultController::addcomment

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting
 
ajax_search:
    path: /search
    controller: App\Controller\DefaultController::searchAction   

