index:
    path: /
    controller: App\Controller\DefaultController::index

category:
    path: /catalog-{id}
    controller: App\Controller\DefaultController::category

categories:
    path: /catalog
    controller: App\Controller\DefaultController::category

product:
    path: /product-{id}
    controller: App\Controller\DefaultController::product

cart:
    path: /cart
    controller: App\Controller\CartController::index

addcomment:
    path: /comment/add
    controller: App\Controller\DefaultController::addcomment